using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QSSAPI.BOL
{
	public class BOL_Sales
	{
		public string ID { get; set; } //int] IDENTITY(1,1) NOT NULL,
		public string sa_ReceiptNo { get; set; } //varchar](50) NULL,
		public string sa_Casher { get; set; } //varchar](50) NULL,
		public string sa_SalesPerson { get; set; } //varchar](50) NULL,
		public string sa_SalesDate { get; set; } //smalldatetime] NULL,
		public string sa_memberno { get; set; } //varchar](50) NULL,
		public string sa_Status { get; set; } //varchar](50) NULL,
		public string sa_CreateDate { get; set; } //smalldatetime] NULL,
		public string sa_Station { get; set; } //varchar](50) NULL,
		public string sa_CancelBy { get; set; } //varchar](50) NULL,
		public string sa_CancelDT { get; set; } //datetime] NULL,
		public string sa_CancelReason { get; set; } //varchar](255) NULL,
		public string sa_uid { get; set; } //varchar](50) NULL,
		public string sa_CustCode { get; set; } //varchar](20) NULL,
		public string sa_DealerCode { get; set; } //varchar](20) NULL,
		public decimal sa_Commission { get; set; } //decimal](18, 4) NULL,
		public int sa_BranchID { get; set; } //int] NULL,
		public int sa_LoyaltyTypeid { get; set; } //int] NULL,
		public string sa_LoyaltyCardno { get; set; } //varchar](50) NULL,
		public string sa_HDSerialNo { get; set; } //varchar](50) NULL,
		public decimal sa_roundingvariance { get; set; } //decimal](18, 2) NULL,
		public string sa_InvoiceNo { get; set; } //varchar](50) NULL,
		public string sa_pmuploaded { get; set; } //varchar](1) NULL,
		public string sa_pmvoiduploaded { get; set; } //varchar](1) NULL,
		public string sa_custom1 { get; set; } //varchar](50) NULL,
		public string sa_custom2 { get; set; } //varchar](50) NULL,
		public string sa_custom3 { get; set; } //varchar](50) NULL,
		public int sa_SMPid { get; set; } //int] NULL,
		public string sa_SMPcode { get; set; } //varchar](20) NULL,
		public string sa_SMPname { get; set; } //varchar](50) NULL,
		public string sa_businessdate { get; set; } //datetime] NULL,
		public string sa_SuspendDate { get; set; } //datetime] NULL,
		public string sa_SuspendDateDayEnd { get; set; } //datetime] NULL,
		public decimal sa_servicecharge { get; set; } //numeric](18, 4) NULL,
		public decimal sa_tax { get; set; } //numeric](18, 4) NULL,
		public string sa_clearbill { get; set; } //varchar](1) NULL,
		public string sa_cancelDTbusinessdate { get; set; } //datetime] NULL,
		public string sa_SalesTime { get; set; } //datetime] NULL,
		public string sa_custom4 { get; set; } //int] NULL,
		public string sa_kdsok { get; set; } //bit] NULL,
		public string sa_kdstime { get; set; } //datetime] NULL,
		public string sa_kdsdt { get; set; } //datetime] NULL,
		public string sa_transtype { get; set; } //varchar](20) NULL,
		public string sa_salestype { get; set; } //varchar](20) NULL,
		public string sa_SuspendBySalesPerson { get; set; } //varchar](50) NULL,
		public string sa_split { get; set; } //bit] NULL,
		public string sa_splitfrom { get; set; } //varchar](30) NULL,
		public string sa_splitseq { get; set; } //int] NULL,
		public string sa_splitseatno { get; set; } //varchar](10) NULL,
		public string sa_BranchDesc { get; set; } //varchar](100) NULL,
		public int sa_BranchGrpID { get; set; } //int] NULL,
		public string sa_BranchGrpDesc { get; set; } //varchar](100) NULL,
		public int sa_RVCID { get; set; } //int] NULL,
		public string sa_RVCDesc { get; set; } //varchar](100) NULL,
		public string sa_PCID { get; set; } //int] NULL,
		public string sa_checkno { get; set; } //varchar](50) NULL,
		public string sa_iid { get; set; } //int] NULL,
		public string sa_printcopy { get; set; } //int] NULL,
		public string sa_SalesTypeSuffix { get; set; } //nvarchar](50) NULL,
		public string sa_datasource { get; set; } //varchar](100) NULL,
		public string sa_printstatus { get; set; } //varchar](50) NULL,
		public string sa_printengine { get; set; } //varchar](50) NULL,
		public string sa_printdt { get; set; } //datetime] NULL,
		public string sa_billtoname { get; set; } //varchar](100) NULL,
		public string sa_billtoadd1 { get; set; } //varchar](250) NULL,
		public string sa_billtoadd2 { get; set; } //varchar](250) NULL,
		public string sa_billtoadd3 { get; set; } //varchar](250) NULL,
		public string sa_billtoadd4 { get; set; } //varchar](250) NULL,
		public string sa_billtoTelno { get; set; } //varchar](100) NULL,
		public string sa_billtoFaxno { get; set; } //varchar](100) NULL,
		public string sa_closecheckrpt { get; set; } //varchar](1) NULL,
		public int sa_shiftid { get; set; } //int] NULL,
		public int sa_shiftno { get; set; } //int] NULL,
		public string sa_shiftrefno { get; set; } //varchar](50) NULL,
		public string sa_sosorderstart { get; set; } //datetime] NULL,
		public string sa_sossubtotalstart { get; set; } //datetime] NULL,
		public string sa_soslastpaymentstart { get; set; } //datetime] NULL,
		public string sa_sosclosedrawer { get; set; } //datetime] NULL,
		public string sa_salespersonname { get; set; } //nvarchar](200) NULL,
		public bool sa_mobile { get; set; } //bit] NULL,
		public string sa_syncdata { get; set; } //nvarchar](2) NULL,
		public string sa_syncvoiddata { get; set; } //nvarchar](2) NULL
		public string sa_expeditionType { get; set; }
		public string sa_token { get; set; }
		public string sa_code { get; set; }
	}
}