using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QSSAPI.BOL
{
    public class BOL_Sales_Details
    {
        public string sd_ID { get; set; } //int] IDENTITY(1,1) NOT NULL,
        public string sd_StockID { get; set; } //int] NULL,
        public string sd_Qty { get; set; } //int] NULL,
        public decimal sd_SPrice { get; set; } //decimal](18, 4) NULL,
        public decimal sd_DiscPercent { get; set; } //numeric](18, 6) NULL,
        public decimal sd_Disc { get; set; } //numeric](18, 6) NULL,
        public string sd_uid { get; set; } //varchar](50) NULL,
        public decimal sd_CostPrice { get; set; } //numeric](18, 6) NULL,
        public string sd_pType { get; set; } //varchar](2) NULL,
        public string sd_VoucherNo { get; set; } //varchar](20) NULL,
        public string sd_UOM { get; set; } //varchar](20) NULL,
        public decimal sd_Contain { get; set; } //numeric](18, 2) NULL,
        public int sd_branchid { get; set; } //int] NULL,
        public string sd_sn { get; set; } //varchar](50) NULL,
        public decimal sd_linepoints { get; set; } //numeric](18, 2) NULL,
        public string sd_Description { get; set; } //nvarchar](255) NULL,
        public string sd_att1 { get; set; } //varchar](20) NULL,
        public string sd_att2 { get; set; } //varchar](20) NULL,
        public string sd_returnfrom { get; set; } //int] NULL,
        public string sd_hd { get; set; } //varchar](30) NULL,
        public string sd_HDSerialNo { get; set; } //varchar](50) NULL,
        public string sd_updateST { get; set; } //varchar](1) NULL,
        public string sd_location { get; set; } //varchar](20) NULL,
        public string sd_export { get; set; } //varchar](1) NULL,
        public string sd_sono { get; set; } //varchar](20) NULL,
        public string sd_promotype { get; set; } //varchar](20) NULL,
        public string sd_promoparentid { get; set; } //int] NULL,
        public string sd_promosdid { get; set; } //int] NULL,
        public decimal sd_spriceBeforeMK { get; set; } //decimal](18, 4) NULL,
        public decimal sd_markdownpercent { get; set; } //decimal](18, 2) NULL,
        public string sd_voucheruid { get; set; } //varchar](20) NULL,
        public string sd_productvoucher { get; set; } //varchar](20) NULL,
        public decimal sd_commissionCompPercent { get; set; } //numeric](18, 2) NULL,
        public decimal sd_commissionCompValue { get; set; } //numeric](18, 2) NULL,
        public decimal sd_commissionTravelPercent { get; set; } //numeric](18, 2) NULL,
        public decimal sd_commissionTravelValue { get; set; } //numeric](18, 2) NULL,
        public decimal sd_commissionPercent { get; set; } //numeric](18, 2) NULL,
        public decimal sd_commissionValue { get; set; } //numeric](18, 2) NULL,
        public decimal sd_commission { get; set; } //numeric](18, 2) NULL,
        public decimal sd_TaxPercent { get; set; } //decimal](18, 4) NULL,
        public decimal sd_TaxAmount { get; set; } //numeric](18, 4) NULL,
        public decimal sd_CommissionCalculationAmt { get; set; } //decimal](18, 4) NULL,
        public string sd_DiscountType { get; set; } //varchar](50) NULL,
        public string sd_SPromo { get; set; } //varchar](200) NULL,
        public string sd_lineextra { get; set; } //nvarchar](500) NULL,
        public string sd_packageparentid { get; set; } //int] NULL,
        public string sd_kitchenhold { get; set; } //bit] NULL,
        public bool sd_kitchenfire { get; set; } //bit] NULL,
        public string sd_kitchenbump { get; set; } //bit] NULL,
        public string sd_kitchenfireon { get; set; } //datetime] NULL,
        public string sd_kitchenfireby { get; set; } //varchar](20) NULL,
        public string sd_kitchenbumpon { get; set; } //datetime] NULL,
        public string sd_kitchenbumpby { get; set; } //varchar](20) NULL,
        public string sd_salestype { get; set; } //varchar](20) NULL,
        public string sd_combopattern { get; set; } //varchar](200) NULL,
        public string sd_combogroup { get; set; } //int] NULL,
        public string sd_cook { get; set; } //bit] NULL,
        public string sd_collect { get; set; } //bit] NULL,
        public decimal sd_actualproduct { get; set; } //numeric](18, 2) NULL,
        public string sd_kitchenprint { get; set; } //bit] NULL,
        public string sd_kitchenprinton { get; set; } //datetime] NULL,
        public string sd_printengine { get; set; } //varchar](20) NULL,
        public string sd_enterby { get; set; } //varchar](20) NULL,
        public string sd_auto { get; set; } //bit] NULL,
        public string sd_refund { get; set; } //varchar](1) NULL,
        public string sd_taxtype { get; set; } //varchar](20) NULL,
        public decimal sd_TaxAmountActual { get; set; } //numeric](18, 4) NULL,
        public decimal sd_svcpercent { get; set; } //numeric](18, 4) NULL,
        public decimal sd_svcamount { get; set; } //numeric](18, 4) NULL,
        public decimal sd_svcamountactual { get; set; } //numeric](18, 4) NULL,
        public string sd_svctype { get; set; } //varchar](50) NULL,
        public string sd_voidremarks { get; set; } //nvarchar](255) NULL,
        public string sd_discountDesc { get; set; } //nvarchar](255) NULL,
        public string sd_resume { get; set; } //varchar](50) NULL,
        public decimal sd_ItemTaxAmount { get; set; } //numeric](18, 4) NULL,
        public decimal sd_ItemTaxAmountActual { get; set; } //numeric](18, 4) NULL,
        public decimal sd_SVCTaxAmount { get; set; } //numeric](18, 4) NULL,
        public decimal sd_SVCTaxAmountActual { get; set; } //numeric](18, 4) NULL,
        public string sd_seatno { get; set; } //varchar](10) NULL,
        public string sd_splitfrom { get; set; } //varchar](30) NULL,
        public string sd_checkno { get; set; } //varchar](50) NULL,
        public string sd_notallowdiscountagain { get; set; } //varchar](1) NULL,
        public decimal sd_AddOnTaxAmountActual { get; set; } //numeric](18, 4) NULL,
        public decimal sd_InclusiveTaxAmountActual { get; set; } //numeric](18, 4) NULL,
        public decimal sd_ItemAddOnTaxAmountActual { get; set; } //numeric](18, 4) NULL,
        public decimal sd_ItemInclusiveTaxAmountActual { get; set; } //numeric](18, 4) NULL,
        public decimal sd_SVCAddOnTaxAmountActual { get; set; } //numeric](18, 4) NULL,
        public decimal sd_SVCInclusiveTaxAmountActual { get; set; } //numeric](18, 4) NULL,
        public string sd_iscondi { get; set; } //bit] NULL,
        public decimal sd_AmtForCalcSVC { get; set; } //numeric](18, 4) NULL,
        public decimal sd_AmtForCalcTax { get; set; } //numeric](18, 4) NULL,
        public string sd_combopatterncbosid { get; set; } //varchar](200) NULL,
        public string sd_combocbosid { get; set; } //varchar](200) NULL,
        public string sd_condiparentid { get; set; } //int] NULL,
        public string sd_comboparentid { get; set; } //int] NULL,
        public string sd_combopatterncount { get; set; } //varchar](200) NULL,
        public string sd_packageparentstockid { get; set; } //int] NULL,
        public string sd_iid { get; set; } //int] NULL,
        public string sd_SalesTypeSuffix { get; set; } //nvarchar](50) NULL,
        public string sd_Casher { get; set; } //varchar](50) NULL,
        public string sd_CasherName { get; set; } //nvarchar](100) NULL,
        public string sd_SalesPerson { get; set; } //varchar](50) NULL,
        public string sd_SalesPersonName { get; set; } //nvarchar](100) NULL,
        public string sd_prttokitchen { get; set; } //varchar](1) NULL,
        public string sd_recipestatus { get; set; } //varchar](1) NULL,
        public string sd_updaterecipe { get; set; } //varchar](1) NULL,
        public string sd_prttoprinter { get; set; } //varchar](100) NULL,
        public decimal sd_weight { get; set; } //decimal](18, 4) NULL,
        public decimal sd_spriceBeforeWeight { get; set; } //decimal](18, 4) NULL,
        public string sd_WeightItem { get; set; } //varchar](1) NULL,
        public string sd_servicechargeid { get; set; } //int] NULL,
        public string sd_servicechargename { get; set; } //varchar](50) NULL,
        public string sd_shiftid { get; set; } //int] NULL,
        public string sd_shiftno { get; set; } //int] NULL,
        public string sd_shiftrefno { get; set; } //varchar](50) NULL,
        public string sd_pcscount { get; set; } //int] NULL,
        public string sd_ComboPatternQty { get; set; } //varchar](50) NULL,
        public decimal sd_TotalInclusivePercentage { get; set; } //numeric](18, 4) NULL,
        public decimal sd_NettAfterDiscountForCalcTax { get; set; } //numeric](18, 4) NULL,
        public decimal sd_Nett { get; set; } //numeric](18, 4) NULL,
        public string sd_fireonthefly { get; set; } //varchar](1) NULL,
        public string sd_fireontheflytime { get; set; } //datetime] NULL,
        public bool sd_kdsend { get; set; } //bit] NULL,
        public string sd_businessdate { get; set; } //datetime] NULL,
        public string sd_UniqueSDID { get; set; } //varchar](50) NULL,
        public string sd_kdsendonthefly { get; set; } //bit] NULL,
        public string sd_mobiletemp { get; set; } //varchar](30) NULL,
        public string sd_syncdata { get; set; } //nvarchar](2) NULL,
        public string sd_syncvoiddata { get; set; } //nvarchar](2) NULL
    }
}